### ISSUE TITLE
Refactoring to C++ classes

### ISSUE THREAD

**Issue by programLyrique** [PRL-PRG/sxpdb#1]
The goal is to simplify the design and use C++ classes.

Something like that:

```C++
class Store {
private:
  std::fstream description_file;//description of the file (types stored, sizes and names of the 3 other files, number of values)
  std::fstream index_file;//hash of value, offset to value in the store, offset to metadata
  std::fstream store_file;//values
  std::fstream metadata_file;//function, package, srcref, number of times seen, offset to the value

  //TODO: write a proper hash class that can automatically give its hash
  // instead of wasting memory
  // Or use std::map?
  std::unordered_map<std::string, size_t> index;

public:
    Store(std::string description_name);

    virtual bool merge_in(std::string filename);

    virtual bool add_value(SEXP val);
    virtual bool have_seen(SEXP val) const;

    virtual SEXP get_value(size_t index) const;

    // Pass it a Description and a Distribution that precises what kind of values
    // we want
    virtual SEXP sample_value() const;

    virtual ~Store() {};
};
```
The goal is to neatly decouple every store, so I think it is better to store the description of the data, not in a global file, but in a description file (we can also have a global file somewhere). In the future, we will also add more metadata (hence , the metadata file).

About using `std::unordered_map` or `std::map`, we should benchmark. If we can reuse the SHA1 hashes directly in the hashtable instead of rehashing them, it might be worth it.

I already added `Store.h` and `Store.cpp` in the main branch but it is probably a better idea to work on that in a different branch (I created branch `cppclasses` for that).

Then, if the store requires to be specialized for some values, we can inherit from that class.

**Comment by programLyrique** [comment]
Actually, an even better design would be to have a thinner base class for Store, without the files, which enables to have two kinds of Stores then:

- `DefaultStore` : which is that one, which can hold any value based on its type, and might be specialized to some types
- `GlobalStore` (which holds several `DefaultStore`, one per type)

Both have the same API I think, so it makes sense.

**Comment by yth** [comment]
So, based on your comment, I think we want something like this:

```class BaseStore {
public:
	BaseStore() {}
	~BaseStore() {}

	virtual bool merge_in(std::string path) { return false; }
	virtual bool add_value(SEXP value) { return false; }

	virtual bool have_seen(SEXP value) const { return false; }
	virtual SEXP get_value(size_t index) const  { return R_NilValue; }
	virtual SEXP sample_value() const { return R_NilValue; }
}

class DefaultStore : BaseStore {
public:
	DefaultStore(std::string path);
	~DefaultStore();

	virtual bool merge_in(std::string path); // from base

	virtual bool add_value(SEXP value); // from base
	virtual bool add_value(std::string value);

	virtual bool have_seen(SEXP value) const; // from base
	virtual bool have_seen(std::string value) const;

	virtual SEXP get_value(size_t index) const; // from base
	virtual std::string get_value(size_t index) const;

	virtual SEXP sample_value() const; // from base
	virtual std::string sample_value() const;

private:
	std::fstream description;
	std::fstream index_file;
	std::fstream data;
	std::fstream metadata;

	std::unordered_map <std::string, size_t> index;
}

class GlobalStore : BaseStore {
public:
	GlobalStore(int *types, std::string metadata_path);
	~GlobalStore();

	virtual bool merge_in(std::string path); // from base

	virtual bool add_value(SEXP value); // from base
	virtual bool add_value(std::string value);

	virtual bool have_seen(SEXP value) const; // from base
	virtual bool have_seen(std::string value) const;

	virtual SEXP get_value(size_t index) const; // from base
	virtual std::string get_value(size_t index) const;

	virtual SEXP sample_value() const; // from base
	virtual std::string sample_value() const;

private:
	DefaultStore *stores;
	int *types;
	std::fstream package_names;
	std::fstream function_names;
	std::fstream srcrefs;

	std::unordered_map <std::string, size_t> package_index;
	std::unordered_map <std::string, size_t> function_index;
	std::unordered_map <std::string, size_t> srcref_index;
}```

**Comment by programLyrique** [comment]
Makes sense. 

I actually started to implement something like that in the `cppclasses` branch. To store the `DefaultStore` in the `GlobalStore`, I'd prefer to use a C++ container (such as `std::vector`) rather than a raw pointer.
 I added back a `sexp_type()` method for the stores  so no need to store the types apart I think. I have not implemented all the methods yet; feel free to implement them.

Why overloading some functions with the `std::string` argument in `DefaultStore` and `GlobalStore`?

What is the purpose of `package_index`, `function_index` and `srcref_index` (and the associated files)?
I think we can store the provenance of each value in a metadata table associated to each store.

**Comment by yth** [comment]
The overloaded methods are to help with merging since we would want those facilities and we would not want to manifest them into a `SEXP`. The `SEXP` version could also use the `std::string` versions as helper functions.

The reason I wanted extra files is that I am worried that it'll be hard to determine a max name length for functions and packages. Instead, we will just store the full names of functions and packages in their respective stores, and we store an index to those stores in the metadata store for the default stores. This way, the size of each data entry is uniform and each data entry doesn't contain a lot of padding.

I am actually not sure quite sure what the `srcref` you mentioned means. I added another store for it just in case.

**Comment by programLyrique** [comment]
Let's just first reproduce  the same functionalities as the C version, as a first step, and so let's leave the metadata out (function, packages, srcref).

 As for the srcref in R, it is an R object that  gives richer information about the location in the source code (`first_line, first_byte, last_line, last_byte, first_column, last_column, first_parsed, last_parsed` in addition to the file name). It is not attached to every step, but mainly to `{`. Maybe it is overkill to store it; will see!

So, for those overloaded methods, I am not sure they should be part of the public API of the class (so, rather `private` or `protected`). Also, we are reading and writing binary blobs, not text, so to show this intent, let's use `std:::vector<char>` instead of `std::string` there.
