### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/sxpdb#13]
Some files in the SXPDB has wrong permissions:

For example
```
-rwx------ 1 pdonatbo r 3.9G Oct 11 17:58 call_ids.bin
```

**Comment by programLyrique** [comment]
In the small database I created and which is in `pipeline-dbgen`?
It's created with whatever default permissions there are in my session.
I adjust the permissions manually when I move them to `/mnt/ocfs_vol_00` usually.

**Comment by programLyrique** [comment]
Actually, I see that for that db:

```bash
total 10287592
-rwxrw-r-- 1 pdonatbo r 4101470712 Oct 11 17:58 call_ids.bin
-rw-rw-r-- 1 pdonatbo r         35 Oct 11 17:58 call_ids.conf
-rw-rw-r-- 1 pdonatbo r    5144944 Oct 11 17:58 call_ids_offsets.bin
-rw-rw-r-- 1 pdonatbo r         43 Oct 11 17:58 call_ids_offsets.conf
...
```

**Comment by fikovnik** [comment]
The bin files were -rwx------. I had to fix manually.

**Comment by programLyrique** [comment]
Some files were create with the Unix `open` . In that case, `open` wants a `mode` flag to give the file permissions.
It was given `S_IRWXU`, meaning, read, write, exec for the user (file owner) but not for the group. I put the right flags to remove the exec permission and add read and write to the group.
