### ISSUE TITLE
Auomatically build indices

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/sxpdb#4]
The `sxpdb::build_indexes` is confusing, would it be possible to build it automatically?

Plus, it does not work if the db is not opened with `mode=T`, yet it does not complain.

**Comment by programLyrique** [comment]
Yes, we should build it automatically after a `merge_all_dbs`! 
In other cases, i.e. merging two small dbs together or adding values manually, I will let the user manually build the db if needed.

Building the indexes in read mode actually builds the indexes in memory, but won't save them on disk. It means that you should be able to do queries during the same session, but next time you open, you won't have the indexes indeed. I agree it's a surprising behaviour so I will just forbid to build indexes in read mode.
