### ISSUE TITLE
Use S3 class for the external point and add checks to API

### ISSUE THREAD

**Issue by fikovnik** [PRL-PRG/sxpdb#8]
The pointer `open_db` returns should have a class and all the API functions should check that the `db` argument is proper. Currently, it segfaults if you pass there anything else.

**Comment by programLyrique** [comment]
The external ptr also has a specific tag that one can check. 
However, adding a class name would help for #6

**Comment by programLyrique** [comment]
The external pointer now has a class, which is used for the S3 API (0f91bafb07b77e5c1a1d314)
Checks are performed directly on the internal tag of the external pointer.
